### PR TITLE
Clarify the push-down accumulator example.

### PR DESCRIPTION
**Pull request by nnethercote**
- Use brackets instead of parens in the push-down accumulator.
- Don't use internal rules, especially given that it's now recommended
  against doing so for performance reasons.
- Remove the `@as_expr` rule, it's not necessary. The final output can
  be produced directly from the `0` accumulator rule.
- Reorder the rules so they are in the easiest-to-follow order.
- Generally reformat to improve readability.

I found this example hard to read when I first encountered it. I think
these changes make it much easier to understand.

### CODE REVIEW

**Comment by Veykril** [comment]
This needs a rebase after #58

**Comment by nnethercote** [comment]
I have rebased.

**Comment by Veykril** [comment]
Thanks!

**Comment by nnethercote** [comment]
Thank you for the fast merges.

**Pull request merged**
